---
- name: setup tool
  hosts: windows
  gather_facts: yes


  tasks: 
    - name: Gather windows system facts
      setup:

    - name: Print gathered facts
      debug:
        msg: "{{ ansible_facts }}"

    -  name: jenkins setup(192.168.0.111:8080)
       win_command: java -jar jenkins.war
       args:
         executable: cmd
         chdir: 'D:\destros\jenkins\'
       #become: yes
       register: jenkinslog
       ignore_errors: true

    -  name: debug
       debug: 
         msg: "{{jenkinslog}}"

       


    -  name: sonar setup(192.168.0.111:9000)
       win_command: D:\destros\sonar\sonarqube\sonarqube-10.6.0.92116\bin\windows-x86-64\StartSonar.bat
       register: sonarlog
       ignore_errors: true

    -  name: debug
       debug: 
         msg: "{{sonarlog}}"

 #-------------------- end of play ---------------------------# 
    
     
