---
- name: setup tool
  hosts: localhost


  tasks: 
    -  name: jenkins setup(192.168.0.111:8080)
       win_command: "D:\destros\jenkins\java -r jenkins.war"
       become: yes
       register: jenkinslog

    -  name: debug
       debug: 
       msg: "(jenkinlog)"

       


    -  name: sonar setup(192.168.0.111:9000)
       win_command: "D:\destros\sonar\sonarqube\sonarqube-10.6.0.92116\bin\windows-x86-64\StartSonar.bat"
       become: yes
       register: sonarlog

    -  name: debug
       debug: 
       msg: "(sonarlog)"

  
    
     
