---
- name: setup tool
  hosts: localhost


  tasks: 
    -  name: jenkins setup(localhost:8080)
       win_shell: java -jar jenkins.war
       args:
         executable: cmd
         chdir: 'D:\destros\jenkins\'
       register: jenkinslog

    -  name: debug
       debug: 
         msg: "(jenkinslog)"

       


    -  name: sonar setup(localhost:9000)
       win_shell: StartSonar.bat
       args:
         executable: cmd
         chdir: 'D:\destros\sonar\sonarqube\sonarqube-10.6.0.92116\bin\windows-x86-64\'
       register: sonarlog

    -  name: debug
       debug: 
         msg: "(sonarlog)"

  
    
     
